INSERT INTO mbti (mbti,title,description) VALUES('intj', '계획 변태', '여행 전부터 이미 완벽한 계획을 세운 당신은, 모든 것을 철저하게 준비하는 계획의 달인이에요. 여행에서의 희열은 계획을 실현하는 데서 오죠.');
INSERT INTO mbti (mbti,title,description) VALUES('intp', '알쓸번잡', '잡학박사 같은 당신은 여행지의 모든 정보를 파악하고, 비효율을 거부하며, 여행 중에도 지식을 나누는 것을 즐겨요. 쓸데없어 보일지라도 당신에겐 소중한 정보들이죠');
INSERT INTO mbti (mbti,title,description) VALUES('infj', '충전형 이타주의자', '타인을 먼저 생각하는 당신은, 여행에서도 다른 사람들의 행복을 최우선으로 삼아요. 조용하고 평화로운 여행지에서 진정한 행복을 느끼죠.');
INSERT INTO mbti (mbti,title,description) VALUES('infp', '낭만적 거절가', '여행을 떠나기 전에는 주저하나, 실제로는 여행을 매우 즐기는 당신. 여행에서의 낭만과 이상을 추구하며, 돌아올 때면 다음 여행을 꿈꾸죠.');
INSERT INTO mbti (mbti,title,description) VALUES('istj', '광기 어린 계획 실천가', '원칙과 계획을 중시하는 당신은 여행에서도 시간 약속과 계획을 철저히 지키며, 어떤 상황에서도 계획대로 움직이는 신뢰할 수 있는 여행자예요.');
INSERT INTO mbti (mbti,title,description) VALUES('istp', '모험 변태', '돌발 상황에서도 흥미를 느끼는 당신은, 여행 중 스릴과 모험을 즐기며, 예기치 않은 일이 발생해도 즐거워하는 진정한 모험가예요.');
INSERT INTO mbti (mbti,title,description) VALUES('isfj', '보살', '모두의 필요를 살피며 조화롭게 여행을 이끄는 당신은, 여행지에서도 따뜻하고 친절한 분위기를 조성해 모두가 즐거운 시간을 보낼 수 있게 해요.');
INSERT INTO mbti (mbti,title,description) VALUES('isfp', '신밧드', '자유분방하고 낭만적인 당신은, 여행에서도 새로운 경험과 환상을 추구하며, 일상에서 벗어난 비현실적인 모험을 즐겨요.');
INSERT INTO mbti (mbti,title,description) VALUES('entj', '짱가형', '철저한 계획과 강한 리더십을 가진 당신은, 여행에서도 문제 해결 능력을 발휘해 어떤 상황에서도 여행을 원활하게 이끌어가는 책임감 있는 여행자예요.');
INSERT INTO mbti (mbti,title,description) VALUES('entp', '박물관 지박령', '새로운 아이디어와 발견에 열정적인 당신은, 여행 중에도 지식을 나누며 모든 것을 재미있고 독특하게 만드는 창의적인 여행자예요.');
INSERT INTO mbti (mbti,title,description) VALUES('enfj', '도라에몽', '타인에게 영감을 주는 당신은, 여행에서도 카리스마와 열정으로 사람들을 이끌고, 깊은 관계 형성에 중점을 두는 따뜻한 여행자예요.');
INSERT INTO mbti (mbti,title,description) VALUES('enfp', '핵인싸', '즉흥적이고 열정적인 당신은, 여행에서도 새로운 사람들과의 만남을 즐기며, 어디서든 즐거움을 찾아내는 사교적인 여행자예요.');
INSERT INTO mbti (mbti,title,description) VALUES('estj', '빨리빨리', '계획적이고 실용적인 당신은, 여행에서도 효율과 질서를 중시하며, 빠르고 정확한 결정으로 여행을 효과적으로 이끄는 실용주의자예요.');
INSERT INTO mbti (mbti,title,description) VALUES('estp', '고집불통', '즉흥적이고 도전적인 당신은, 여행에서도 새로운 경험을 적극적으로 추구하며, 어떤 상황에서도 자신만의 방식으로 여행을 즐기는 자유로운 영혼이에요.');
INSERT INTO mbti (mbti,title,description) VALUES('esfj', '광고형 여행자', '친절하고 사교적인 당신은, 여행에서도 모든 순간을 기록하고 공유하며, 주변 사람들과 함께 즐거운 추억을 만들어가는 활기찬 여행자예요.');
INSERT INTO mbti (mbti,title,description) VALUES('esfp', '합석 장인', '사람들과 어울리는 것을 사랑하는 당신은, 여행에서도 새로운 만남과 즐거운 경험을 추구하며, 어디서나 친구를 만들어 즐거운 시간을 보내는 사교적인 여행자예요.');
